### ISSUE TITLE
Question regarding to captcha_token

### ISSUE THREAD

**Issue by gaara4896** [MokuMoki/popcat_bot#1]
In the original request send out by `popcat.click`, there is a google captcha request being send out before the actual request to register the click. But it seemed that you had attached `mokumoki` as the token and it is still returning 201. 

The best case scenario is there is no server validation done in place. However, what I was worry is how the architecture is set up, and if that is the case, then these requests wouldn't count anymore (done asynchronously after the response had been sent to the client).

**Comment by MokuMoki** [comment]
Thanks for opening an issue about this. The script was written according to another simpler one that just perform fetch using the API with [random captcha token value](https://forum.gamer.com.tw/C.php?bsn=60076&snA=6513339). Of course, we have no idea if the server does accept the count value after that.

We have commited a change on the script, where we will simply use the token provided by reCAPTCHA and send the request. We then take the token response and attach it in next request.

**Comment by gaara4896** [comment]
Cool work there. Kudos for the effort
