### ISSUE TITLE
Popdog bot bug

### ISSUE THREAD

**Issue by cycool29** [MokuMoki/popcat_bot#8]
The popdog bot seem have a bug on showing to console?
![image](https://user-images.githubusercontent.com/88134003/130356489-c0fcaa5a-012b-4811-87a3-dec032e1ce30.png)
It just like clicking 1 time every time …
Well I check the network tab and found that the packet sent show 2000 clicks, so this should be bug showing to console...
![image](https://user-images.githubusercontent.com/88134003/130356583-febffe87-623c-44cb-b67a-b424082a4066.png)
Note: I put the script on Tampermonkey so it runs automatically when the page loads

**English is not my first language so please excuse any grammar mistakes ...*

**Comment by MokuMoki** [comment]
Hi, I have attempted to reproduce the issue by running the script through Tampermonkey but I can't get the bug to show up:
![image](https://user-images.githubusercontent.com/14260598/130366148-9efd250d-50aa-41b7-8ea2-61449f29fc96.png)

Since the console is outputting the server data response (i.e. what the server received and stored), I suspect the server might have shadowbanned your uuid and only increment your score by 1 despite sending 2000. Still, just my own speculation and there might be simpler reason such as the problem in your script.

Do update if you still experiencing the same issue.

**Comment by cycool29** [comment]
I found I've been banned by Popdog...... Clear cookies and get a new uuid fixed the problem. Thanks!

**Comment by ryancheok05** [comment]
> Hi, I have attempted to reproduce the issue by running the script through Tampermonkey but I can't get the bug to show up:
> ![image](https://user-images.githubusercontent.com/14260598/130366148-9efd250d-50aa-41b7-8ea2-61449f29fc96.png)
> 
> Since the console is outputting the server data response (i.e. what the server received and stored), I suspect the server might have shadowbanned your uuid and only increment your score by 1 despite sending 2000. Still, just my own speculation and there might be simpler reason such as the problem in your script.
> 
> Do update if you still experiencing the same issue.

Can I know how to run this script in tampermonkey?

**Comment by cycool29** [comment]
> Can I know how to run this script in tampermonkey?

Just install tampermonkey [here](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en). Click on tampermonkey extension button and from the dropdown select `Create a new script`. Delete all and paste this front-matter there:
```
// ==UserScript==
// @name         Popdog
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Pophub bot by MokuMoki
// @author       MokuMoki
// @match        https://popdog.click/play
// @icon         https://www.google.com/s2/favicons?domain=popdog.click
// @grant        none
// ==/UserScript==
```
then place popdog code below it.

If you want to put other Pop types just create a new script, paste the front-matter and change `@name`, `@match` and `@icon` and paste your desired Pophub code below it.

**Comment by ryancheok05** [comment]
> > Can I know how to run this script in tampermonkey?
> 
> Just install tampermonkey [here](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en). Click on tampermonkey extension button and from the dropdown select `Create a new script`. Delete all and paste this front-matter there:
> 
> ```
> // ==UserScript==
> // @name         Popdog
> // @namespace    http://tampermonkey.net/
> // @version      0.1
> // @description  Pophub bot by MokuMoki
> // @author       MokuMoki
> // @match        https://popdog.click/play
> // @icon         https://www.google.com/s2/favicons?domain=popdog.click
> // @grant        none
> // ==/UserScript==
> ```
> 
> then place popdog code below it.
> 
> If you want to put other Pop types just create a new script, paste the front-matter and change `@name`, `@match` and `@icon` and paste your desired Pophub code below it.

Thank you very much!
