### ISSUE TITLE
bug auto click popdog

### ISSUE THREAD

**Issue by ghost** [MokuMoki/popcat_bot#9]
all of a sudden without doing anything, the bot bug and stops working and this error message appears: VM63:10 POST https://popdog.click/clicked/v2 429
requester @ VM63:10
VM63:29 SyntaxError: Unexpected token D in JSON at position 0 

would it be possible to fix this problem?

![Capture d’écran (47)](https://user-images.githubusercontent.com/87788410/130465482-8d804dcf-0f1a-4d3c-b553-8fa8441c6e7c.png)

**Comment by MokuMoki** [comment]
Hi. This is CloudFlare rejecting your request and timed out your IP. It should happen less often by tuning up the `interval`  to something like 5 seconds. Example: `const interval = 5000` .
